services:
  docker-proxy:
    image: ghcr.io/vansour/docker-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.debian
    container_name: docker-proxy
    ports:
      - "8080:8080"
    restart: unless-stopped
