[server]
host = "0.0.0.0"
port = 8080

[log]
logFilePath = "/app/logs/docker-proxy.log"
level = "info" # debug, info, warn, error

[proxy]
default = "registry-1.docker.io" #registry-1.docker.io, ghcr.io ...
