[server]
host = "0.0.0.0"
port = 8080

[log]
logFilePath = "/app/logs/docker-proxy.log"
level = "info" # debug, info, warn, error

[proxy]
default = "docker.io" #docker.io, ghcr.io ...

[auth]
ghcr-token = ""
